-- =============================================================================
-- Inspect auto-increment sequences for this project
-- =============================================================================
-- Run: psql -U postgres -d loan_db -f list_sequences.sql
-- =============================================================================

SELECT
    c.relname AS table_name,
    a.attname AS column_name,
    pg_get_serial_sequence(c.relname, a.attname) AS sequence_name,
    CASE a.attidentity
        WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
        WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
        ELSE 'SERIAL / sequence default'
    END AS id_generation_type
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid
WHERE n.nspname = 'public'
  AND c.relkind = 'r'
  AND a.attnum > 0
  AND NOT a.attisdropped
  AND a.attname = 'id'
  AND c.relname IN (
      'users',
      'loan_applications',
      'notifications',
      'documents',
      'kyc_details',
      'credit_scores'
  )
ORDER BY c.relname;

SELECT
    sequencename,
    last_value,
    start_value,
    increment_by
FROM pg_sequences
WHERE schemaname = 'public'
  AND sequencename LIKE '%\_id\_seq' ESCAPE '\'
ORDER BY sequencename;
